server:
  port: 8082
  servlet:
    contextPath: /AdvancedWeb
spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/advancedwebdb?user=root
    driverClassName: com.mysql.cj.jdbc.Driver